/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './components/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './contexts/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
    './services/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'hsl(var(--bg-primary) / <alpha-value>)',
        'bg-secondary': 'hsl(var(--bg-secondary) / <alpha-value>)',
        surface: 'hsl(var(--surface) / <alpha-value>)',
        'surface-secondary': 'hsl(var(--surface-secondary) / <alpha-value>)',
        'surface-tertiary': 'hsl(var(--surface-tertiary) / <alpha-value>)',
        'surface-inset': 'hsl(var(--surface-inset) / <alpha-value>)',
        border: 'hsl(var(--border) / <alpha-value>)',
        'border-primary': 'hsl(var(--border-primary) / <alpha-value>)',
        'border-secondary': 'hsl(var(--border-secondary) / <alpha-value>)',
        'text-primary': 'hsl(var(--text-primary) / <alpha-value>)',
        'text-secondary': 'hsl(var(--text-secondary) / <alpha-value>)',
        'text-muted': 'hsl(var(--text-muted) / <alpha-value>)',
        accent: 'hsl(var(--accent) / <alpha-value>)',
        'on-accent': 'hsl(var(--on-accent) / <alpha-value>)',
        'secondary-accent': 'hsl(var(--secondary-accent) / <alpha-value>)',
        info: 'hsl(var(--info) / <alpha-value>)',
        success: 'hsl(var(--success) / <alpha-value>)',
        warning: 'hsl(var(--warning) / <alpha-value>)',
        error: 'hsl(var(--error) / <alpha-value>)',
        'team-blue': 'hsl(var(--team-blue) / <alpha-value>)',
        'team-red': 'hsl(var(--team-red) / <alpha-value>)',
        // Aliases
        gold: 'hsl(var(--accent) / <alpha-value>)',
        'gold-bright': 'hsl(var(--accent) / <alpha-value>)',
        'on-gold': 'hsl(var(--on-accent) / <alpha-value>)',
        turquoise: 'hsl(var(--secondary-accent) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Teko', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      fontSize: {
        h1: ['2.5rem', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['2rem', { lineHeight: '1.25', fontWeight: '600' }],
        h3: ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        h4: ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        small: ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        tiny: ['0.75rem', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
